project:
  type: website
  output-dir: docs
website:
  title: "AIML Course"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: pages/slt/logistic-regression/index.qmd
      #   text: Logistic Regression
  sidebar:
    style: "docked"
    logo: "./images/aiml_logo.png"
    search: true
    collapse-level: 2
    contents:
      - icon: logistic
        text: Logistic Regression
        href: pages/slt/logistic-regression/index.qmd
      - icon: svm
        text: SVM & LA
        href: pages/slt/svm/index.qmd
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This Website is created using `Quarto` and Published as Github Pages"
    type: primary
    position: below-navbar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  


