project:
  type: website
  output-dir: docs
website:
  title: "Artificial Intelligence and Machine Learning"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: logistic.qmd
        text: Logistic Regression
  sidebar:
    style: "docked"
    logo: "./images/user_image.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com
      # - icon: twitter
      #   text: Twitter
      #   url: https://twitter.com
      - icon: Email
      - text: "Email"
        url: mailto:tech4alltraining@gmail.com
      - text: "ORCID"
        url: https://orcid.org/<orcid-id>
      - text: "Google Scholar"
        url: https://scholar.google.com/citations?user=<google-scholar-user>
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This Website is created using `Quarto` and Published as Github Pages"
    type: primary
    position: below-navbar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  


